name: 'Dependabot2Discord'

on:
  schedule:
    - cron: '0 */6 * * *' 

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: 0xTeles/GetDependaBotAlert@stable
        with:
          token: ${{ secrets.TOKEN }}
          slack_webhook: ${{ secrets.WEBHOOK }}